version: '3'

services:
    web:
        build: .
        container_name: belajar_django_blog
        command: gunicorn myproject.wsgi:application --bind 0.0.0.0:9009
        volumes:
            - .:/app
        ports:
            - "9009:9009"